### ISSUE TITLE
broken urls

### ISSUE THREAD

**Issue by 7c00** [MikaGuraNTK/kurumi-web#2]
There are 3 or more broken urls:
* one in README.md, which is being fixed by #1 
* one in [index.html#L19](https://github.com/MikaGuraNTK/kurumi-web/blob/2ca1aa64ffb90b6bd44a872460ffdf26e0d057ce/index.html#L19)
* one in [kurumi.js#L2](https://github.com/MikaGuraNTK/kurumi-web/blob/2ca1aa64ffb90b6bd44a872460ffdf26e0d057ce/kurumi.js#L2)

**Comment by MikaGuraNTK** [comment]
抱歉，没看到 ，马上改 :)
